# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-thumb}
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aleksander Williams"]
  s.date = %q{2010-11-20}
  s.email = %q{alekswilliams@earthlink.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "example/file.ru",
    "example/frank.rb",
    "example/public/images/imagick.jpg",
    "example/static.ru",
    "lib/rack/thumb.rb",
    "rack-thumb.gemspec",
    "spec/base_spec.rb",
    "spec/helpers.rb",
    "spec/media/imagick.jpg"
  ]
  s.homepage = %q{http://github.com/akdubya/rack-thumb}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Drop-in image thumbnailing for your Rack stack.}
  s.test_files = [
    "spec/base_spec.rb",
    "spec/helpers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mapel>, [">= 0.1.6"])
      s.add_development_dependency(%q<bacon>, [">= 0"])
    else
      s.add_dependency(%q<mapel>, [">= 0.1.6"])
      s.add_dependency(%q<bacon>, [">= 0"])
    end
  else
    s.add_dependency(%q<mapel>, [">= 0.1.6"])
    s.add_dependency(%q<bacon>, [">= 0"])
  end
end

