# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rack-thumb 0.2.4 ruby lib

Gem::Specification.new do |s|
  s.name = "rack-thumb".freeze
  s.version = "0.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Aleksander Williams".freeze]
  s.date = "2020-12-08"
  s.email = "alekswilliams@earthlink.net".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "example/file.ru",
    "example/frank.rb",
    "example/public/images/imagick.jpg",
    "example/static.ru",
    "lib/rack/mapel.rb",
    "lib/rack/thumb.rb",
    "rack-thumb.gemspec",
    "spec/base_spec.rb",
    "spec/helpers.rb",
    "spec/mapel_spec.rb",
    "spec/media/imagick.jpg",
    "spec/media/rotated.jpg"
  ]
  s.homepage = "http://github.com/akdubya/rack-thumb".freeze
  s.rubygems_version = "3.0.6".freeze
  s.summary = "Drop-in image thumbnailing for your Rack stack.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<mapel>.freeze, [">= 0.1.6"])
      s.add_development_dependency(%q<bacon>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rack>.freeze, [">= 0"])
      s.add_dependency(%q<mapel>.freeze, [">= 0.1.6"])
      s.add_dependency(%q<bacon>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>.freeze, [">= 0"])
    s.add_dependency(%q<mapel>.freeze, [">= 0.1.6"])
    s.add_dependency(%q<bacon>.freeze, [">= 0"])
  end
end

